site_name: Ultralytics YOLO Docs
repo_url: https://github.com/ultralytics/yolov5
repo_name: Ultralytics

theme:
  name: "material"
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.tabs.link
markdown_extensions:
  # Div text decorators
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Syntax highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # button
  - attr_list

  # content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocstrings

nav:
  - Quickstart: quickstart.md
  - CLI: cli.md
  - Python API: api.md
  - explanation.md